import type { Metadata } from "next";
import { Afacad, Aboreto } from "next/font/google";
import "./globals.css";
import HeroPage from "./hero/page";
import JoinPage from "./join/page";
import Footer from "@/components/Footer";

const afacad = Afacad({
  variable: "--font-afacad",
  subsets: ["latin"],
});

const aboreto = Aboreto({
  variable: "--font-aboreto",
  subsets: ["latin"],
  weight : ['400']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${afacad.variable} ${aboreto.variable} antialiased`}
      >
        <HeroPage/>
        {children}
        <JoinPage/>
        <Footer/>
      </body>
    </html>
  );
}
